NotDirectlyEditableException: Add @since tag
Follows-Up: Iee7350dfddb130696189cfb158455cdcd44e3302
Change-Id: Id5fb3f858005f7105567b0d4b3a5ce88f1d9e134